# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: coffee_custom
  theme_night:
  font: Native
  font_size: m

# SEO

marketing:
  seo:
    site_type: Project
    local_business_type: ''
    org_name: 'cloud-native.wiki'
    description: 'Hugo based static site for Cloud-Native learning'
    twitter: 'avijit_tweeter'
  analytics:
    google_analytics: 'G-73PKQ8R5J1'
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''  
  verification:
    google: 'google-site-verification=C4ydo602MekWD4rbR7MSE1vp4G0gGoHVLiyvI-G5Vd8'
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: false
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: true
      share_alike: true
      allow_commercial: true

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    theme_light: github-dark
    theme_dark: dracula
  math:
    enable: false
  privacy_pack:
    enable: true
  repository:
    url: 'https://github.com/avijitliberty/cloud-native'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: 'giscus'
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: 'avijitliberty/cloud-native'
      repo_id: 'R_kgDOKYv3hA'
      category_id: 'DIC_kwDOKYv3hM4CagjD'
      theme: light
      language_code: en
      mapping: pathname
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
